[xml]
alignment = """
    <data id="data.sim" dataType="{{datatype}}">
        {{#taxa}}
        <sequence taxon="{{.}}">?</sequence>
        {{/taxa}}
    </data>
"""


[defaults]
datatype = "binary"
