[xml]
clock_model = """
<branchRateModel id="clock" spec="BurstClock" perSplit="@perSplit">
    <branchonlyClock id="innerClock" spec="beast.evolution.branchratemodel.UCRelaxedClockModel" rates="@branchRates" tree="@tree" clock.rate="@clockRate">
        <LogNormal id="logNormal:ucldStdev:clock" meanInRealSpace="true" name="distr" M="1.0" S="@ucldStdev:clock" />
    </branchonlyClock>
</branchRateModel>
"""

parameters = """
        <stateNode id="clockRate" spec="RealParameter" lower="0.0">{{clock_rate}}</stateNode>
        <stateNode id="ucldStdev:clock" spec="RealParameter" estimate="false" lower="0.0" upper="3.0" value="{{clock_stdev}}"/>
        <stateNode id="branchRates" spec="RealParameter" dimension="{{n_rates}}" lower="0.0">1.0</stateNode>
        <stateNode id="perSplit" spec="RealParameter" estimate="true">{{per_split}}</stateNode>
"""

priors = """
        <prior id="branchRatesPrior" name="distribution" x="@branchRates">
            <distr spec="LogNormalDistributionModel" meanInRealSpace="true" M="1.0" S="@ucldStdev:clock" />
        </prior>
        <prior id="clockRatePrior" name="distribution" x="@clockRate">
            <distr spec="LogNormalDistributionModel" meanInRealSpace="true" M="0.35" S="0.5"/>
        </prior>
        <prior id="PerSplitPrior" name="distribution" x="@perSplit">
            <distr spec="beast.math.distributions.Normal" mean="0.0" sigma="0.05"/>
        </prior>
"""

_priors = """

"""

operators = """
    <operator id="clockRateScaler" spec="ScaleOperator" parameter="@clockRate" scaleFactor="0.9" weight="8.0"/>
    <operator id="branchRatesRandomWalk" spec="RealRandomWalkOperator" parameter="@branchRates" windowSize="0.2" weight="6.0"/>
    <operator id="branchRatesScaleOperator" spec="ScaleOperator" parameter="@branchRates" scaleFactor="0.85" weight="6.0"/>
    <operator id="RatesSwapOperator" spec="SwapOperator" parameter="@branchRates" weight="2.0"/>
    
    <operator id="BurstClockRandomWalk" spec="RealRandomWalkOperator" windowSize="0.15" parameter="@perSplit" useGaussian="true" weight="5.0"/>

"""

_operators = """
    <operator id="ucldStdevScaler.c:clock" spec="ScaleOperator" parameter="@ucldStdev:clock" scaleFactor="0.5" weight="2.0"/>
    <operator id="branchRatesUcldStdevScaler" spec="consoperators.UcldScalerOperator"
          rates="@branchRates" stdev="@ucldStdev:clock" distr="@logNormal:ucldStdev:clock" scaleFactor="0.5" weight="3.0"/>
"""

priorOperators = """
    <operator id="clockRateScaler" spec="ScaleOperator" parameter="@clockRate" scaleFactor="0.2" weight="8.0"/>
    <operator id="branchRatesRandomWalk" spec="RealRandomWalkOperator" parameter="@branchRates" windowSize="0.2" weight="6.0"/>
    <operator id="branchRatesScaleOperator" spec="ScaleOperator" parameter="@branchRates" scaleFactor="0.8" weight="6.0"/>
    <operator id="RatesSwapOperator" spec="SwapOperator" parameter="@branchRates" weight="2.0"/>
    <operator id="BurstClockRandomWalk" spec="RealRandomWalkOperator" windowSize="0.25" parameter="@perSplit" useGaussian="true" weight="5.0"/>
"""

logs = """
        <log idref="clockRate"/>
        <log idref="ucldStdev:clock"/>
        <log idref="perSplit"/>
        <log idref="branchRates"/>
"""

_logs = """
        <log branchratemodel="@clock" spec="beast.evolution.branchratemodel.RateStatistic" tree="@tree"/>
"""

groundTruthLogs = """
        <log id="sim.clockRate" spec="RealParameter" value="{{clockRate}}" />
        <log id="sim.perSplit" spec="RealParameter" value="{{perSplit}}" />
        <log id="sim.branchRates" spec="RealParameter" value="{{branchRates}}" />
"""

[defaults]
clock_rate = 0.35
clock_stdev = 0.5
per_split = 0.0
